language: python
python:
  - "2.7"

sudo: required

before_script:
  - apt-get install -y clang
  - apt-get install -y llvm
  - python -V                                   # Print out python version for debugging
  - pip install -r requirements.txt
  - pip install coverage

script:
  - coverage run --source=src test.py test
  - coveralls

notifications:
  email:
    recipients:
      - dollking@kookmin.ac.kr
    on_success: always
    on_failure: always