sudo: required
dist: trusty

language: python
python:
  - "2.7"

before_script:
  - sudo apt-get remove -y clang
  - sudo apt-get install -y clang
  - sudo apt-get install -y libclang-dev
  - clang --version
  - python -V                                   # Print out python version for debugging
  - pip install -r requirements.txt
  - pip install pytest-cov==2.4.0
  - pip install coveralls==1.1
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libclang.so.1 /usr/lib/x86_64-linux-gnu/libclang.so

script:
  - coverage run --source=readablecode tests/test.py
#  - py.test --cov readablecode tests/test.py

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - dollking@kookmin.ac.kr
    on_success: always
    on_failure: always