language: python
python:
  - "2.7"


before_script:
  - apt-get install -y clang
  - apt-get install -y llvm
  - python -V                                   # Print out python version for debugging
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
  - ls

script:
  - coverage run --source=src /tests/test.py

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - dollking@kookmin.ac.kr
    on_success: always
    on_failure: always