sudo: required
dist: precise

language: python
python:
  - "2.7"

before_script:
  - clang --version
  - python -V                                   # Print out python version for debugging
  - pip install -r requirements.txt
  - pip install --upgrade clang==5.0.0
  - pip install pytest-cov==2.4.0
  - pip install coveralls==1.1
  - pip install -U .

script:
  - coverage run --source=readablecode tests/test.py
#  - py.test --cov readablecode tests/test.py

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - dollking@kookmin.ac.kr
    on_success: always
    on_failure: always